permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

title : Jonathan C Dickinson
description:
disqus_shortname: dickinsons

owner:
  name: Jonathan Dickinson
  bio: "Software Developer."
  twitter: jcdickinson
  github: jcdickinson

production_url : http://jcdickinson.github.io
url: //jcdickinson.github.io

timezone:    Africa/Johannesburg
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : dickinsons

  analytics :
    provider : false

  sharing :
    provider : false
